# Generated by Django 5.2.5 on 2025-09-08 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('tiendas', '0001_initial'),
        ('ventas', '0004_movimientocredito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'permissions': [('can_sell', 'Puede realizar ventas'), ('view_own_sales', 'Puede ver sus propias ventas'), ('view_own_purchases', 'Puede ver sus propias compras')]},
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='tiendas.tienda'),
        ),
    ]
