# Generated by Django 5.2.5 on 2025-09-03 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '__first__'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('largo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('imagen', models.URLField(blank=True)),
                ('proveedores', models.ManyToManyField(blank=True, related_name='productos', to='proveedores.proveedor')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda')),
            ],
        ),
    ]
