# Generated by Django 5.2.5 on 2025-09-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tiene_credito', models.BooleanField(default=False)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='tiendas.tienda')),
            ],
        ),
    ]
